volumes:
  db_data:
  static:
  media:

services:
  web:
    container_name: barter_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    environment:
      SECRET_KEY: django
      DEBUG: "True"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: barter
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      DJANGO_SUPERUSER_EMAIL: admin@test.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: sh -c " sleep 10 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:14.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: barter
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
