# Generated by Django 5.2 on 2025-04-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
